// UDISKEN: Linux drive automounter for the impatient.
// Copyright (C) BlackMa9ick
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <https://www.gnu.org/licenses/>.

/// Interfaces proxies and functions acting upon them.

#include "interfaces.hpp"

#include "globals.hpp"
#include "utilities.hpp"

#include <libnotify/notification.h>
#include <sdbus-c++/Error.h>
#include <sdbus-c++/IConnection.h>
#include <sdbus-c++/ProxyInterfaces.h>
#include <sdbus-c++/Types.h>
#include <spdlog/spdlog.h>
#include <udisks-sdbus-c++/udisks_errors.hpp>


namespace interfaces {

UdisksBlock::UdisksBlock(sdbus::IConnection& connection,
                         const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, sdbus::ServiceName{globals::kInterfaceName},
                      object_path) {
  registerProxy();
}

UdisksDrive::UdisksDrive(sdbus::IConnection& connection,
                         const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, globals::kServiceName, object_path) {
  registerProxy();
}

UdisksFilesystem::UdisksFilesystem(sdbus::IConnection& connection,
                                   const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, globals::kServiceName, object_path) {
  registerProxy();
}

// FIXME(BlackMa9ick): seemingly no methods generated by sdbus-c++ are marked
// const...
auto GetMountPoints(UdisksFilesystem& fs) -> MountPoints {
  return conversions::ConvertArrayArrayByte(fs.MountPoints());
}

void PrintMountPoints(const MountPoints& mnt_points) {
  spdlog::debug("Current mount points:");
  for (const auto& current_mnt_points : mnt_points) {
    spdlog::debug("- {}", current_mnt_points);
  }
}

UdisksPartition::UdisksPartition(sdbus::IConnection& connection,
                                 const sdbus::ObjectPath& objectPath)
    : ProxyInterfaces<Partition_proxy>(connection, globals::kServiceName,
                                       objectPath) {
  registerProxy();
}

}  // namespace interfaces

// TEST(blackma9ick): constructing an UdisksFilesystem mounts the filesystem, if
// automounting is enabled; do not fail if filesystem is already mounted (e.g.
// by user)
// TEST(blackma9ick): destructing an UdisksFilesystem unmounts the filesystem,
// if automounting if enabled; do not fail if filesystem is already unmounted
// (e.g. by external program).
