// UDISKEN: Linux drive automounter for the impatient.
// Copyright (C) 2025 BlackMa9ick
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <https://www.gnu.org/licenses/>.

/// Udisks objects, interface proxies, managers and related functions.
/// Contains the entrypoints to most of UDISKEN's logic, such as automounting.

#include "udisks.hpp"

#include "options.hpp"
#include "utilities.hpp"

#include <libnotify/notification.h>
#include <sdbus-c++/Error.h>
#include <sdbus-c++/IConnection.h>
#include <sdbus-c++/ProxyInterfaces.h>
#include <sdbus-c++/Types.h>
#include <spdlog/spdlog.h>
#include <udisks-sdbus-c++/udisks_errors.hpp>

#include <map>
#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace interfaces {

UdisksBlock::UdisksBlock(sdbus::IConnection& connection,
                         const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, sdbus::ServiceName{udisks::kInterfaceName},
                      object_path) {
  registerProxy();
}

UdisksDrive::UdisksDrive(sdbus::IConnection& connection,
                         const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, udisks::kServiceName, object_path) {
  registerProxy();
}

UdisksFilesystem::UdisksFilesystem(sdbus::IConnection& connection,
                                   const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, udisks::kServiceName, object_path) {
  registerProxy();
}

// Seemingly no methods generated by sdbus-c++ are marked
// const... Can't mark this const.
auto GetMountPoints(UdisksFilesystem& fs) -> MountPoints {
  return utils::ConvertArrayArrayByte(fs.MountPoints());
}

void PrintMountPoints(const MountPoints& mnt_points) {
  spdlog::debug("Current mount points:");
  for (const auto& current_mnt_points : mnt_points) {
    spdlog::debug("- {}", current_mnt_points);
  }
}

UdisksLoop::UdisksLoop(sdbus::IConnection& connection,
                       const sdbus::ObjectPath& objectPath)
    : ProxyInterfaces<Loop_proxy>(connection, udisks::kServiceName,
                                  objectPath) {
  registerProxy();
}

UdisksPartition::UdisksPartition(sdbus::IConnection& connection,
                                 const sdbus::ObjectPath& objectPath)
    : ProxyInterfaces<Partition_proxy>(connection, udisks::kServiceName,
                                       objectPath) {
  registerProxy();
}

}  // namespace interfaces

// TEST(blackma9ick): constructing an UdisksFilesystem mounts the filesystem, if
// automounting is enabled; do not fail if filesystem is already mounted (e.g.
// by user)
// TEST(blackma9ick): destructing an UdisksFilesystem unmounts the filesystem,
// if automounting if enabled; do not fail if filesystem is already unmounted
// (e.g. by external program).

namespace objects {

Drive::Drive(std::unique_ptr<interfaces::UdisksDrive> drive)
    : drive_{std::move(drive)} {
  if (!drive_) {
    throw std::invalid_argument("drive pointer must not be null");
  }
}

auto Drive::ObjectPath() const -> const sdbus::ObjectPath& {
  return drive_->getProxy().getObjectPath();
}

auto Drive::drive() -> interfaces::UdisksDrive& { return *drive_; }

BlockDevice::BlockDevice(
    std::unique_ptr<interfaces::UdisksBlock> block,
    std::unique_ptr<interfaces::UdisksFilesystem> filesystem,
    std::unique_ptr<interfaces::UdisksLoop> loop,
    std::unique_ptr<interfaces::UdisksPartition> partition)
    : block_{std::move(block)},
      filesystem_{std::move(filesystem)},
      loop_{std::move(loop)},
      partition_{std::move(partition)} {
  if (!block_) {
    throw std::invalid_argument("block pointer must not be null");
  }

  if (block_->HasDrive()) {
    drive_ = std::make_unique<Drive>(std::make_unique<interfaces::UdisksDrive>(
        block_->getProxy().getConnection(), block_->Drive()));
  }
}

[[nodiscard]] auto BlockDevice::ObjectPath() const -> const sdbus::ObjectPath& {
  return block_->getProxy().getObjectPath();
}

auto BlockDevice::filesystem() -> interfaces::UdisksFilesystem& {
  if (!HasFilesystem()) {
    throw std::logic_error("object does not implement interface");
  }

  return *filesystem_;
}

auto BlockDevice::loop() -> interfaces::UdisksLoop& {
  if (!HasLoop()) {
    throw std::logic_error("object does not implement interface");
  }

  return *loop_;
}

auto BlockDevice::partition() -> interfaces::UdisksPartition& {
  if (!HasPartition()) {
    throw std::logic_error("object does not implement interface");
  }

  return *partition_;
}

namespace {

namespace udisks = org::freedesktop::UDisks2;

auto Mount(interfaces::UdisksFilesystem& fs) -> std::optional<std::string> {
  try {
    auto mnt_point = fs.Mount({});

    interfaces::PrintMountPoints(interfaces::GetMountPoints(fs));

    return mnt_point;
  } catch (const sdbus::Error& e) {
    if (e.getName() ==
        udisks::ErrorName(udisks::UdisksErrors::kUdisksErrorAlreadyMounted)) {
      spdlog::warn(
          "{} is already mounted but UDisks initially returned no mount paths;",
          fs.getProxy().getObjectPath().c_str());
      interfaces::PrintMountPoints(interfaces::GetMountPoints(fs));

      return std::nullopt;
    }

    spdlog::error("Failed to automount:\n({}) {}", e.getName().c_str(),
                  e.getMessage());

    throw;
  }
}

void PrintNotAutomounting(const BlockDevice& blk_device,
                          std::string_view reason) {
  spdlog::debug("Not automounting {}: {}", blk_device.ObjectPath().c_str(),
                reason);
}

}  // namespace

auto TryAutomount(BlockDevice& blk_device) -> std::optional<std::string> {
  if (!blk_device.block().HintAuto()) {
    PrintNotAutomounting(blk_device, "automount hint was false");

    return std::nullopt;
  }

  // Could there even not be a filesystem if HintAuto was false?
  if (!blk_device.HasFilesystem()) {
    PrintNotAutomounting(blk_device, "no filesystem found");

    return std::nullopt;
  }

  // If mount points already exist, no need to automount it...
  // TODO(blackma9ick): ...unless other paths are given to UDISKEN and it
  // should mount?)
  if (!blk_device.filesystem().MountPoints().empty()) {
    PrintNotAutomounting(blk_device, "already mounted");

    return std::nullopt;
  }

  auto mnt_point = Mount(blk_device.filesystem());

  if (mnt_point) {
    spdlog::info("Automounted {}", *mnt_point);
    utils::Notification notif{
        .summary = "Mounted disk",
        .body =
            std::format("{} at {}", blk_device.block().HintName(), *mnt_point),
        .icon = blk_device.block().HintIconName()};
    utils::Notify(notif);
  }

  return mnt_point;
}

}  // namespace objects

namespace managers {

UdisksManager::UdisksManager(sdbus::IConnection& connection)
    : ProxyInterfaces(connection, sdbus::ServiceName{udisks::kInterfaceName},
                      sdbus::ObjectPath{kObjectPath}) {
  registerProxy();
}

UdisksObjectManager::UdisksObjectManager(sdbus::IConnection& connection,
                                         options::Options options)
    : ProxyInterfaces(connection, sdbus::ServiceName{udisks::kInterfaceName},
                      sdbus::ObjectPath{udisks::kObjectPath}),
      options_{options} {
  for (auto managed_objects = GetManagedObjects();
       const auto& [object_path, interfaces_and_properties] : managed_objects) {
    onInterfacesAdded(object_path, interfaces_and_properties);
  }

  spdlog::info("Parsed existing drives");

  registerProxy();
}

namespace {

template <class UdisksInterface>
auto HasInterface(InterfacesAndProperties& inp) -> bool {
  return inp.contains(sdbus::InterfaceName{UdisksInterface::INTERFACE_NAME});
}

}  // namespace

void UdisksObjectManager::onInterfacesAdded(
    const sdbus::ObjectPath& object_path,
    InterfacesAndProperties interfaces_and_properties) {
  spdlog::debug("New object: {}", object_path.c_str());

  if (!HasInterface<interfaces::UdisksBlock>(interfaces_and_properties)) {
    return;
  }

  auto block = std::make_unique<interfaces::UdisksBlock>(
      getProxy().getConnection(), object_path);

  std::unique_ptr<interfaces::UdisksFilesystem> filesystem{};
  if (HasInterface<interfaces::UdisksFilesystem>(interfaces_and_properties)) {
    filesystem = std::make_unique<interfaces::UdisksFilesystem>(
        getProxy().getConnection(), object_path);
  }

  std::unique_ptr<interfaces::UdisksLoop> loop{};
  if (HasInterface<interfaces::UdisksLoop>(interfaces_and_properties)) {
    loop = std::make_unique<interfaces::UdisksLoop>(getProxy().getConnection(),
                                                    object_path);
  }

  std::unique_ptr<interfaces::UdisksPartition> partition{};
  if (HasInterface<interfaces::UdisksPartition>(interfaces_and_properties)) {
    partition = std::make_unique<interfaces::UdisksPartition>(
        getProxy().getConnection(), object_path);
  }

  // Only block must be non-null. The rest can be null. The Drive member will be
  // automatically constructed if it exists.
  objects::BlockDevice blk_device{std::move(block), std::move(filesystem),
                                  std::move(loop), std::move(partition)};

  if (options::MountEnabled()) {
    objects::TryAutomount(blk_device);
  }

  block_devices_.try_emplace(object_path, std::move(blk_device));

  spdlog::debug("Added Block device at {}", object_path.c_str());
}

void UdisksObjectManager::onInterfacesRemoved(
    [[maybe_unused]] const sdbus::ObjectPath& object_path,
    [[maybe_unused]] const std::vector<sdbus::InterfaceName>& interfaces) {
  // for (const auto& interface : interfaces) {
  // }
}

}  // namespace managers
