// UDISKEN: Linux drive automounter for the impatient.
// Copyright (C) BlackMa9ick
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <https://www.gnu.org/licenses/>.

/// Udisks objects, interface proxies, managers and related functions.

#include "udisks.hpp"

#include "utilities.hpp"

#include <libnotify/notification.h>
#include <sdbus-c++/Error.h>
#include <sdbus-c++/IConnection.h>
#include <sdbus-c++/ProxyInterfaces.h>
#include <sdbus-c++/Types.h>
#include <spdlog/spdlog.h>
#include <udisks-sdbus-c++/udisks_errors.hpp>

#include <map>
#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace interfaces {

UdisksBlock::UdisksBlock(sdbus::IConnection& connection,
                         const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, sdbus::ServiceName{udisks::kInterfaceName},
                      object_path) {
  registerProxy();
}

UdisksDrive::UdisksDrive(sdbus::IConnection& connection,
                         const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, udisks::kServiceName, object_path) {
  registerProxy();
}

UdisksFilesystem::UdisksFilesystem(sdbus::IConnection& connection,
                                   const sdbus::ObjectPath& object_path)
    : ProxyInterfaces(connection, udisks::kServiceName, object_path) {
  registerProxy();
}

// FIXME(BlackMa9ick): seemingly no methods generated by sdbus-c++ are marked
// const...
auto GetMountPoints(UdisksFilesystem& fs) -> MountPoints {
  return conversions::ConvertArrayArrayByte(fs.MountPoints());
}

void PrintMountPoints(const MountPoints& mnt_points) {
  spdlog::debug("Current mount points:");
  for (const auto& current_mnt_points : mnt_points) {
    spdlog::debug("- {}", current_mnt_points);
  }
}

UdisksPartition::UdisksPartition(sdbus::IConnection& connection,
                                 const sdbus::ObjectPath& objectPath)
    : ProxyInterfaces<Partition_proxy>(connection, udisks::kServiceName,
                                       objectPath) {
  registerProxy();
}

}  // namespace interfaces

// TEST(blackma9ick): constructing an UdisksFilesystem mounts the filesystem, if
// automounting is enabled; do not fail if filesystem is already mounted (e.g.
// by user)
// TEST(blackma9ick): destructing an UdisksFilesystem unmounts the filesystem,
// if automounting if enabled; do not fail if filesystem is already unmounted
// (e.g. by external program).

namespace objects {

Drive::Drive(std::unique_ptr<interfaces::UdisksDrive> drive)
    : drive_{std::move(drive)} {
  if (!drive_) {
    throw std::invalid_argument("drive pointer must not be null");
  }
}

auto Drive::ObjectPath() const -> const sdbus::ObjectPath& {
  return drive_->getProxy().getObjectPath();
}

auto Drive::drive() -> interfaces::UdisksDrive& { return *drive_; }

BlockDevice::BlockDevice(
    std::unique_ptr<interfaces::UdisksBlock> block,
    std::unique_ptr<interfaces::UdisksFilesystem> filesystem,
    std::unique_ptr<interfaces::UdisksLoop> loop,
    std::unique_ptr<interfaces::UdisksLoop> partition)
    : block_{std::move(block)},
      filesystem_{std::move(filesystem)},
      loop_{std::move(loop)},
      partition_{std::move(partition)} {
  if (!block_) {
    throw std::invalid_argument("block pointer must not be null");
  }

  if (block_->HasDrive()) {
    drive_ = std::make_unique<Drive>(std::make_unique<interfaces::UdisksDrive>(
        block_->getProxy().getConnection(), block_->Drive()));
  }
}

[[nodiscard]] auto BlockDevice::ObjectPath() const -> const sdbus::ObjectPath& {
  return block_->getProxy().getObjectPath();
}

namespace {

namespace udisks = org::freedesktop::UDisks2;

auto Mount(interfaces::UdisksFilesystem& fs) -> std::optional<std::string> {
  try {
    auto mnt_point = fs.Mount({});

    interfaces::PrintMountPoints(interfaces::GetMountPoints(fs));

    return mnt_point;
  } catch (const sdbus::Error& e) {
    if (e.getName() ==
        udisks::ErrorName(udisks::UdisksErrors::kUdisksErrorAlreadyMounted)) {
      spdlog::warn(
          "{} is already mounted but UDisks initially returned no mount paths;",
          fs.getProxy().getObjectPath().c_str());
      interfaces::PrintMountPoints(interfaces::GetMountPoints(fs));

      return std::nullopt;
    }

    spdlog::error("Failed to automount:\n({}) {}", e.getName().c_str(),
                  e.getMessage());

    throw;
  }
}

}  // namespace

auto TryMount(objects::BlockDevice& blk_device) -> std::optional<std::string> {
  auto print_not_automounting = [&blk_device](std::string_view reason) {
    spdlog::debug("Not automounting {}: {}", blk_device.ObjectPath().c_str(),
                  reason);
  };

  if (!blk_device.block().HintAuto()) {
    print_not_automounting("automount hint was false");

    return std::nullopt;
  }

  // Could there even not be a filesystem if HintAuto was false?
  if (!blk_device.HasFilesystem()) {
    print_not_automounting("no filesystem found");

    return std::nullopt;
  }

  // If mount points already exist, no need to automount it...
  // TODO(blackma9ick): ...unless other paths are given to UDISKEN and it
  // should mount?)
  if (!blk_device.filesystem().MountPoints().empty()) {
    print_not_automounting("already mounted");

    return std::nullopt;
  }

  auto mnt_point = Mount(blk_device.filesystem());

  if (mnt_point.has_value()) {
    spdlog::info("Automounted {}", *mnt_point);
    utils::Notification notif{
        .summary = "Mounted disk",
        .body =
            std::format("{} at {}", blk_device.block().HintName(), *mnt_point),
        .icon = "drive-removable-media"};
    utils::Notify(notif);
  }

  return mnt_point;
}

auto BlockDevice::filesystem() -> interfaces::UdisksFilesystem& {
  if (!HasFilesystem()) {
    throw std::logic_error("interface does not exist");
  }

  return *filesystem_;
}

auto BlockDevice::loop() -> interfaces::UdisksLoop& {
  if (!HasLoop()) {
    throw std::logic_error("interface does not exist");
  }

  return *loop_;
}

auto BlockDevice::partition() -> interfaces::UdisksLoop& {
  if (!HasPartition()) {
    throw std::logic_error("interface does not exist");
  }

  return *partition_;
}

}  // namespace objects

namespace managers {

UdisksManager::UdisksManager(sdbus::IConnection& connection)
    : ProxyInterfaces(connection, sdbus::ServiceName{udisks::kInterfaceName},
                      sdbus::ObjectPath{kObjectPath}) {
  registerProxy();
}

UdisksObjectManager::UdisksObjectManager(sdbus::IConnection& connection)
    : ProxyInterfaces(connection, sdbus::ServiceName{udisks::kInterfaceName},
                      sdbus::ObjectPath{udisks::kObjectPath}) {
  for (auto managed_objects = GetManagedObjects();
       const auto& [object_path, interfaces_and_properties] : managed_objects) {
    onInterfacesAdded(object_path, interfaces_and_properties);
  }

  registerProxy();
}

void UdisksObjectManager::onInterfacesAdded(
    const sdbus::ObjectPath& object_path,
    const std::map<sdbus::InterfaceName,
                   std::map<sdbus::PropertyName, sdbus::Variant>>&
        interfaces_and_properties) {
  spdlog::debug("New object: {}", object_path.c_str());

  if (interfaces_and_properties.contains(
          sdbus::InterfaceName{interfaces::UdisksBlock::INTERFACE_NAME}) &&
      interfaces_and_properties.contains(
          sdbus::InterfaceName{interfaces::UdisksFilesystem::INTERFACE_NAME})) {
    objects::BlockDevice blk_device{
        std::make_unique<interfaces::UdisksBlock>(getProxy().getConnection(),
                                                  object_path),
        std::make_unique<interfaces::UdisksFilesystem>(
            getProxy().getConnection(), object_path)};

    block_devices_.try_emplace(object_path, std::move(blk_device));

    spdlog::debug("Added Block device at {}", object_path.c_str());
  }
}

void UdisksObjectManager::onInterfacesRemoved(
    [[maybe_unused]] const sdbus::ObjectPath& object_path,
    [[maybe_unused]] const std::vector<sdbus::InterfaceName>& interfaces) {
  // for (const auto& interface : interfaces) {
  // }
}

}  // namespace managers
